name: aly_oss_example
version: 0.0.1
description: Demonstrates how to use the aly_oss plugin.
publish_to: 'none'

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  aly_oss:
    path: ../

flutter:
  uses-material-design: true
