name: aly_oss_example
version: 0.0.1
description: Demonstrates how to use the aly_oss plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  image_picker: ^0.6.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  aly_oss:
    path: ../

flutter:

#  assets:
#    - assets/tower.jpg
